# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501

import typing

from nautilus_trader import model

__all__ = [
    "BINANCE_PAPI",
    "BINANCE_PAPI_CLIENT_ID",
    "BINANCE_PAPI_VENUE",
    "BinancePapiExecutionClientConfig",
    "BinancePapiExecutionClientFactory",
]

BINANCE_PAPI: str
BINANCE_PAPI_CLIENT_ID: model.ClientId
BINANCE_PAPI_VENUE: model.Venue

@typing.final
class BinancePapiExecutionClientConfig:
    def __init__(self, account_id: model.AccountId | None = None) -> None: ...
    @property
    def account_id(self) -> model.AccountId: ...

@typing.final
class BinancePapiExecutionClientFactory:
    def __init__(self) -> None: ...
    def name(self) -> str: ...
