# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501

import typing

from nautilus_trader import model

__all__ = [
    "BINANCE_PAPI",
    "BINANCE_PAPI_CLIENT_ID",
    "BINANCE_PAPI_VENUE",
    "BinancePapiAccountSession",
    "BinancePapiExecutionClientConfig",
    "BinancePapiExecutionClientFactory",
    "BinancePapiReadOnlyClient",
    "BinancePapiReadOnlyConfig",
    "BinancePapiReadOnlySnapshot",
]

BINANCE_PAPI: str
BINANCE_PAPI_CLIENT_ID: model.ClientId
BINANCE_PAPI_VENUE: model.Venue

@typing.final
class BinancePapiAccountSession:
    def __init__(
        self, config: BinancePapiReadOnlyConfig, instruments: typing.Sequence[typing.Any]
    ) -> None: ...
    def start(self) -> typing.Awaitable[None]: ...
    def stop(self) -> typing.Awaitable[None]: ...
    def evidence_json(self) -> str: ...
    @property
    def is_connected(self) -> bool: ...
    @property
    def is_synchronized(self) -> bool: ...

@typing.final
class BinancePapiExecutionClientConfig:
    def __init__(
        self,
        account_id: model.AccountId | None = None,
        read_only: BinancePapiReadOnlyConfig | None = None,
        instrument_ids: typing.Sequence[model.InstrumentId] | None = None,
    ) -> None: ...
    @property
    def account_id(self) -> model.AccountId: ...
    @property
    def read_only(self) -> BinancePapiReadOnlyConfig | None: ...
    @property
    def instrument_ids(self) -> list[model.InstrumentId]: ...

@typing.final
class BinancePapiExecutionClientFactory:
    def __init__(self) -> None: ...
    def name(self) -> str: ...

@typing.final
class BinancePapiReadOnlyClient:
    def __init__(
        self, config: BinancePapiReadOnlyConfig, instruments: typing.Sequence[typing.Any]
    ) -> None: ...
    def cancel(self) -> None: ...
    @property
    def is_throttled(self) -> bool: ...
    def refresh_account_observations(self) -> typing.Awaitable[None]: ...
    def account_observations_json(self, max_receipt_age_ms: int) -> str: ...
    def account_snapshot_json(
        self, max_receipt_age_ms: int, max_collection_span_ms: int
    ) -> str: ...
    def query_order_rate_limit(self) -> typing.Awaitable[str]: ...
    def generate_mass_status(
        self, start: int, end: int
    ) -> typing.Awaitable[BinancePapiReadOnlySnapshot]: ...
    def generate_open_order_status_reports(
        self, instrument_id: model.InstrumentId | None = None
    ) -> typing.Awaitable[list[model.OrderStatusReport]]: ...
    def generate_position_status_reports(
        self, instrument_id: model.InstrumentId | None = None
    ) -> typing.Awaitable[list[model.PositionStatusReport]]: ...
    def generate_order_status_report(
        self,
        instrument_id: model.InstrumentId,
        venue_order_id: model.VenueOrderId | None = None,
        client_order_id: model.ClientOrderId | None = None,
    ) -> typing.Awaitable[model.OrderStatusReport]: ...

@typing.final
class BinancePapiReadOnlyConfig:
    def __init__(
        self,
        account_id: model.AccountId,
        api_key: str,
        api_secret: str,
        base_url: str | None = None,
        websocket_url: str | None = None,
        proxy_url: str | None = None,
        request_timeout_ms: int | None = None,
        operation_timeout_ms: int | None = None,
        max_requests: int | None = None,
        max_rows: int | None = None,
        listen_key_keepalive_interval_ms: int | None = None,
        transport_rotation_interval_ms: int | None = None,
        recovery_lookback_ms: int | None = None,
        refresh_debounce_ms: int | None = None,
        max_websocket_message_bytes: int | None = None,
        max_websocket_buffer_messages: int | None = None,
        max_websocket_buffer_bytes: int | None = None,
    ) -> None: ...
    @property
    def account_id(self) -> model.AccountId: ...
    @property
    def request_timeout_ms(self) -> int: ...
    @property
    def operation_timeout_ms(self) -> int: ...
    @property
    def max_requests(self) -> int: ...
    @property
    def max_rows(self) -> int: ...
    @property
    def listen_key_keepalive_interval_ms(self) -> int: ...
    @property
    def transport_rotation_interval_ms(self) -> int: ...
    @property
    def recovery_lookback_ms(self) -> int: ...
    @property
    def refresh_debounce_ms(self) -> int: ...
    @property
    def max_websocket_message_bytes(self) -> int: ...
    @property
    def max_websocket_buffer_messages(self) -> int: ...
    @property
    def max_websocket_buffer_bytes(self) -> int: ...
    @property
    def has_proxy_url(self) -> bool: ...

@typing.final
class BinancePapiReadOnlySnapshot:
    def mass_status(self) -> model.ExecutionMassStatus: ...
    @property
    def window_end(self) -> int: ...
    @property
    def reports_complete(self) -> bool: ...
    def instrument_ids(self) -> list[model.InstrumentId]: ...
    def issues(self) -> list[str]: ...
    def to_json(self) -> str: ...
